avg_train_accuracy: 0.029
avg_train_loss: 0.026
avg_type: avg
dataset: emnist-balanced
epochs: 2
frac: 0.5
iid: 0
kernel_num: 9
kernel_sizes: 3,4,5
local_bs: 256
local_ep: 10
lr: 0.01
max_pool: 'True'
model: cnn
momentum: 0.2
norm: batch_norm
num_channels: 1
num_classes: 47
num_filters: 32
num_users: 10
number_of_classes_of_half_of_user: 3
optimizer: sgd
seed: 1
test_accuracy_list:
- 0.028244680851063828
- 0.04930851063829787
test_loss_list:
- 565.0366377830505
- 557.2470359802246
train_accuracy:
- 0.023
- 0.029
train_loss:
- 3.29
- 2.65
unequal: 0
verbose: 1
