avg_train_accuracy: 0.529
avg_train_loss: 0.027
avg_type: avg_n_classes
dataset: emnist-balanced
epochs: 2
frac: 0.1
iid: 0
kernel_num: 9
kernel_sizes: 3,4,5
local_bs: 256
local_ep: 10
lr: 0.01
max_pool: 'True'
model: cnn
momentum: 0.2
norm: batch_norm
num_channels: 1
num_classes: 47
num_filters: 32
num_users: 10
number_of_classes_of_half_of_user: 6
optimizer: sgd
seed: 1
test_accuracy_list:
- 0.06601063829787233
- 0.1854787234042553
test_loss_list:
- 628.7557244300842
- 809.5790667533875
train_accuracy:
- 0.177
- 0.529
train_loss:
- 3.549
- 2.712
unequal: 0
verbose: 1
