avg_train_accuracy: 0.006
avg_train_loss: 0.004
avg_type: avg
dataset: emnist-balanced
epochs: 2
frac: 0.3
iid: 0
kernel_num: 9
kernel_sizes: 3,4,5
local_bs: 256
local_ep: 10
lr: 0.01
max_pool: 'True'
model: cnn
momentum: 0.2
norm: batch_norm
num_channels: 1
num_classes: 47
num_filters: 32
num_users: 10
number_of_classes_of_half_of_user: 2
optimizer: sgd
seed: 1
test_accuracy_list:
- 0.023510638297872342
- 0.06813829787234042
test_loss_list:
- 638.2329874038696
- 1060.1819229125977
train_accuracy:
- 0.0
- 0.006
train_loss:
- 1.897
- 0.433
unequal: 0
verbose: 1
